export const CHANGE_WORKSHEET_TITLE = 'CHANGE_WORKSHEET_TITLE';

export const ADD_BUDGET_ITEM = 'ADD_BUDGET_ITEM';
export const EDIT_BUDGET_ITEM = 'EDIT_BUDGET_ITEM';
export const DELETE_BUDGET_ITEM = 'DELETE_BUDGET_ITEM';
